name: Continuous Integration

on: [pull_request]

jobs:
  LintAndTest:
    name: Lint And Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint
